create extension if not exists pgcrypto;

create table public.conversations (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null default 'New conversation',
  provider_id text not null,
  model text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.messages (
  id uuid primary key default gen_random_uuid(),
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  sequence bigint generated by default as identity,
  role text not null check (role in ('system', 'user', 'assistant', 'tool')),
  content jsonb not null default '[]'::jsonb,
  status text not null default 'complete' check (status in ('streaming', 'complete', 'error', 'cancelled')),
  provider_metadata jsonb not null default '{}'::jsonb,
  idempotency_key text,
  created_at timestamptz not null default now(),
  unique (conversation_id, sequence),
  unique (user_id, idempotency_key)
);

create index conversations_user_updated_idx on public.conversations (user_id, updated_at desc);
create index messages_conversation_sequence_idx on public.messages (conversation_id, sequence);

alter table public.conversations enable row level security;
alter table public.messages enable row level security;

create policy "users manage their conversations" on public.conversations
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "users manage their messages" on public.messages
  for all using (
    auth.uid() = user_id and exists (
      select 1 from public.conversations c
      where c.id = conversation_id and c.user_id = auth.uid()
    )
  ) with check (
    auth.uid() = user_id and exists (
      select 1 from public.conversations c
      where c.id = conversation_id and c.user_id = auth.uid()
    )
  );

create or replace function public.touch_conversation()
returns trigger language plpgsql security invoker set search_path = '' as $$
begin
  update public.conversations set updated_at = now() where id = new.conversation_id;
  return new;
end;
$$;

create trigger messages_touch_conversation
after insert or update on public.messages
for each row execute function public.touch_conversation();
